#!/bin/bash

read -p "Ingrese el nombre de su Barrio: " neighborhood
read -p "Ingrese la direccion de la comisaría màs cercana: " policeStationAdress
read -p "Ingrese la primera calle de la comisaría: " street1
read -p "Ingrese la segunda calle de la comisaría: " street2

echo "La comisaría de $neighborhood se encuentra en la calle $policeStationAdress entre las calles $street1 y $street2"

exit 0
