#!/bin/bash

read -p "Ingrese un caracter: " character

case $character in
	"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9")
		echo "El carácter es un número"
    ;;
    
	"a" | "e" | "i" | "o" | "u")
		echo "El carácter es un vocal"
    ;;
    
	*) 
		echo "El carácter es una consonante"
    ;;
esac

exit 0
